language: r
sudo: required
warnings_are_errors: true
bioc_packages: SVGAnnotation
env:
  global:
    - NOT_CRAN=true
before_install: echo "options(repos = c(CRAN='http://cran.rstudio.com'))" > ~/.Rprofile
